# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       mesa-x86-radeon

# >> macros
# << macros

Summary:    Mesa graphics libraries built for Radeon
Version:    9.2.0
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://www.mesa3d.org/beta
Source0:    %{name}-%{version}.tar.bz2
Source100:  mesa-x86-radeon.yaml
BuildRequires:  pkgconfig(glproto)
BuildRequires:  pkgconfig(dri2proto) >= 1.1
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(libdrm) >= 2.4.30
BuildRequires:  pkgconfig(xxf86vm)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xfixes)
BuildRequires:  pkgconfig(xdamage)
BuildRequires:  pkgconfig(xi)
BuildRequires:  pkgconfig(xmu)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(talloc)
BuildRequires:  pkgconfig(libudev) >= 160
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig autoconf automake
BuildRequires:  expat-devel >= 2.0
BuildRequires:  python
BuildRequires:  libxml2-python
BuildRequires:  bison
BuildRequires:  flex
BuildRequires:  makedepend
BuildRequires:  llvm
BuildRequires:  llvm-devel
BuildRequires:  gettext

%description
Mesa is an open-source implementation of the OpenGL specification  -
a system for rendering interactive 3D graphics.


%package libglapi
Summary:    Mesa shared gl api library
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libglapi
Mesa shared gl api library.

%package libgbm
Summary:    Mesa GBM runtime libraries
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libgbm
Mesa GBM runtime library.

%package libgbm-devel
Summary:    Mesa libGBM development package
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   mesa-x86-radeon-libgbm = %{version}-%{release}
Provides:   libgbm = %{version}-%{release}

%description libgbm-devel
Mesa libGLESv2 development package.

%package libGLESv2
Summary:    Mesa libGLESv2 runtime libraries
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libGLESv2 = %{version}-%{release}

%description libGLESv2
Mesa libGLESv2 runtime library.

%package libGLESv2-compat
Summary:    Mesa libGLESv2 runtime compatibility library
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libGLESv2.so.2
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libGLESv2.so

%description libGLESv2-compat
Mesa libGLESv2 runtime compatibility library.

%package libEGL
Summary:    Mesa libEGL runtime libraries and DRI drivers
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libEGL = %{version}-%{release}

%description libEGL
Mesa libEGL runtime library.

%package libEGL-compat
Summary:    Mesa libEGL runtime compatibility library
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libEGL.so.1
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libEGL.so

%description libEGL-compat
Mesa libEGL runtime compatibility library.

%package libglapi-devel
Summary:    Mesa libglapi development package
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   mesa-x86-radeon-libglapi = %{version}-%{release}
Provides:   libglapi-devel

%description libglapi-devel
Mesa libglapi development package.

%package libGLESv2-devel
Summary:    Mesa libGLESv2 development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   mesa-x86-radeon-libGLESv2 = %{version}-%{release}
Provides:   libGLESv2-devel
Obsoletes:  mesa-x86-radeon-libGLESv2-compat

%description libGLESv2-devel
Mesa libGLESv2 development packages

%package libEGL-devel
Summary:    Mesa libEGL development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   mesa-x86-radeon-libEGL = %{version}-%{release}
Provides:   libEGL-devel
Obsoletes:  mesa-x86-radeon-libEGL-compat

%description libEGL-devel
Mesa libEGL development packages

%package libGL
Summary:    Mesa libGL runtime libraries and DRI drivers
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libGL = %{version}-%{release}

%description libGL
Mesa libGL runtime library.

%package libGL-devel
Summary:    Mesa libGL development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   mesa-x86-radeon-libGL = %{version}-%{release}
Requires:   libX11-devel
Provides:   libGL-devel

%description libGL-devel
Mesa libGL development packages

%package libdricore%{version}
Summary:    Mesa-based DRI runtime library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libdricore%{version} = %{version}-%{release}

%description libdricore%{version}
Mesa-based DRI runtime library.

%package libwayland-egl
Summary:    Mesa libwayland EGL runtime libraries
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libwayland-egl = %{version}-%{release}

%description libwayland-egl
Mesa libwayland EGL runtime library.

%package libwayland-egl-devel
Summary:    Mesa libwayland EGL development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   mesa-x86-radeon-libwayland = %{version}-%{release}
Provides:   libwayland-egl-devel

%description libwayland-egl-devel
Mesa libwayland EGL development packages

%package dri-drivers-devel
Summary:    Mesa-based DRI development files
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description dri-drivers-devel
Mesa-based DRI driver development files.

%package dri-radeon-driver
Summary:    Mesa-based DRI drivers
Group:      Graphics/Display and Graphics Adaptation
Requires:   %{name} = %{version}-%{release}
Provides:   mesa-dri-drivers = %{version}-%{release}

%description dri-radeon-driver
Mesa-based i965 DRI driver.

%package dri-swrast-driver
Summary:    Mesa-based DRI drivers
Group:      Graphics/Display and Graphics Adaptation
Requires:   %{name} = %{version}-%{release}
Provides:   mesa-x86-radeon-dri-drivers = %{version}-%{release}

%description dri-swrast-driver
Mesa-based swrast DRI driver.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
cd mesa
# << build pre

%reconfigure --disable-static \
    --enable-gles2 \
    --disable-gallium-egl \
    --with-egl-platforms=wayland,drm \
    --enable-gbm \
    --enable-shared-glapi \
    --with-gallium-drivers=r300,r600,swrast \
    --enable-glx-tls \
    --enable-glx \
    --with-dri-drivers=radeon,r200

make %{?jobs:-j%jobs}

# >> build post
cd ..
# << build post

%install
rm -rf %{buildroot}
# >> install pre
cd mesa
# << install pre
%make_install

# >> install post

# strip out undesirable headers
pushd $RPM_BUILD_ROOT%{_includedir}/GL
rm [a-fh-np-wyz]*.h
rm osmesa.h
popd
cd ..
# << install post

%post libglapi -p /sbin/ldconfig

%postun libglapi -p /sbin/ldconfig

%post libgbm -p /sbin/ldconfig

%postun libgbm -p /sbin/ldconfig

%post libGLESv2 -p /sbin/ldconfig

%postun libGLESv2 -p /sbin/ldconfig

%post libGLESv2-compat -p /sbin/ldconfig

%postun libGLESv2-compat -p /sbin/ldconfig

%post libEGL -p /sbin/ldconfig

%postun libEGL -p /sbin/ldconfig

%post libEGL-compat -p /sbin/ldconfig

%postun libEGL-compat -p /sbin/ldconfig

%post libGL -p /sbin/ldconfig

%postun libGL -p /sbin/ldconfig

%post libdricore%{version} -p /sbin/ldconfig

%postun libdricore%{version} -p /sbin/ldconfig

%post libwayland-egl -p /sbin/ldconfig

%postun libwayland-egl -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
# << files

%files libglapi
%defattr(-,root,root,-)
%{_libdir}/libglapi.so.0
%{_libdir}/libglapi.so.0.*
# >> files libglapi
# << files libglapi

%files libgbm
%defattr(-,root,root,-)
%{_libdir}/libgbm.so.1
%{_libdir}/libgbm.so.1.0.0
# >> files libgbm
# << files libgbm

%files libgbm-devel
%defattr(-,root,root,-)
%{_libdir}/libgbm.so
%{_libdir}/pkgconfig/gbm.pc
%{_includedir}/gbm.h
# >> files libgbm-devel
# << files libgbm-devel

%files libGLESv2
%defattr(-,root,root,-)
%{_libdir}/libGLESv2.so.2
%{_libdir}/libGLESv2.so.2.0.0
# >> files libGLESv2
# << files libGLESv2

%files libGLESv2-compat
%defattr(-,root,root,-)
%{_libdir}/libGLESv2.so
# >> files libGLESv2-compat
# << files libGLESv2-compat

%files libEGL
%defattr(-,root,root,-)
%{_libdir}/libEGL.so.1
%{_libdir}/libEGL.so.1.0.0
# >> files libEGL
# << files libEGL

%files libEGL-compat
%defattr(-,root,root,-)
%{_libdir}/libEGL.so
# >> files libEGL-compat
# << files libEGL-compat

%files libglapi-devel
%defattr(-,root,root,-)
%{_libdir}/libglapi.so
# >> files libglapi-devel
# << files libglapi-devel

%files libGLESv2-devel
%defattr(-,root,root,-)
%{_libdir}/libGLESv2.so
%{_includedir}/GLES2/gl2.h
%{_includedir}/GLES2/gl2ext.h
%{_includedir}/GLES2/gl2platform.h
%{_includedir}/GLES3/gl3.h
%{_includedir}/GLES3/gl3ext.h
%{_includedir}/GLES3/gl3platform.h
%{_libdir}/pkgconfig/glesv2.pc
# >> files libGLESv2-devel
# << files libGLESv2-devel

%files libEGL-devel
%defattr(-,root,root,-)
%{_libdir}/libEGL.so
%dir %{_includedir}/EGL
%{_includedir}/EGL/egl.h
%{_includedir}/EGL/eglext.h
%{_includedir}/EGL/eglplatform.h
%{_includedir}/EGL/eglmesaext.h
%dir %{_includedir}/KHR
%{_includedir}/KHR/khrplatform.h
%{_libdir}/pkgconfig/egl.pc
# >> files libEGL-devel
# << files libEGL-devel

%files libGL
%defattr(-,root,root,-)
%{_libdir}/libGL.so.*
# >> files libGL
# << files libGL

%files libGL-devel
%defattr(-,root,root,-)
%{_includedir}/GL/gl.h
%{_includedir}/GL/gl_mangle.h
%{_includedir}/GL/glext.h
%{_includedir}/GL/glx.h
%{_includedir}/GL/glx_mangle.h
%{_includedir}/GL/glxext.h
%dir %{_includedir}/GL/internal
%{_includedir}/GL/internal/dri_interface.h
%{_libdir}/libGL.so
%{_libdir}/pkgconfig/gl.pc
# >> files libGL-devel
# << files libGL-devel

%files libdricore%{version}
%defattr(-,root,root,-)
%{_libdir}/libdricore%{version}.so
%{_libdir}/libdricore%{version}.so.*
%{_sysconfdir}/drirc
# >> files libdricore%{version}
# << files libdricore%{version}

%files libwayland-egl
%defattr(-,root,root,-)
%{_libdir}/libwayland-egl.so.1
%{_libdir}/libwayland-egl.so.1.0.0
# >> files libwayland-egl
# << files libwayland-egl

%files libwayland-egl-devel
%defattr(-,root,root,-)
%{_libdir}/pkgconfig/wayland-egl.pc
%{_libdir}/libwayland-egl.so
# >> files libwayland-egl-devel
# << files libwayland-egl-devel

%files dri-drivers-devel
%defattr(-,root,root,-)
%{_libdir}/pkgconfig/dri.pc
# >> files dri-drivers-devel
# << files dri-drivers-devel

%files dri-radeon-driver
%defattr(-,root,root,-)
%{_libdir}/dri/r200_dri.so
%{_libdir}/dri/r300_dri.so
%{_libdir}/dri/r600_dri.so
%{_libdir}/dri/radeon_dri.so
# >> files dri-radeon-driver
# << files dri-radeon-driver

%files dri-swrast-driver
%defattr(-,root,root,-)
%{_libdir}/dri/swrast_dri.so
# >> files dri-swrast-driver
# << files dri-swrast-driver
